import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ka';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.shop': 'Shop',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.dashboard': 'Dashboard',
    'nav.cart': 'Cart',
    'nav.hive.details': 'Hive Details',
    'nav.alerts': 'Alerts',
    'nav.add.hive': 'Add Hive',
    'nav.settings': 'Settings',
    
    // Landing Page
    'landing.hero.title': 'Smart Beehive',
    'landing.hero.subtitle': 'Monitoring',
    'landing.hero.description': 'Protect your colonies with AI-powered thermal imaging, real-time sensors, and intelligent alerts. Detect varroa mites early and optimize hive health.',
    'landing.hero.cta.trial': 'Start Free Trial',
    'landing.hero.cta.shop': 'Shop Devices',
    'landing.hero.benefits.trial': '30-day free trial',
    'landing.hero.benefits.card': 'No credit card required',
    'landing.stats.hives': 'Hives Monitored',
    'landing.stats.accuracy': 'Mite Detection Accuracy',
    'landing.stats.reduction': 'Reduced Colony Loss',
    'landing.stats.monitoring': 'Continuous Monitoring',
    'landing.features.title': 'Everything you need to protect your hives',
    'landing.features.subtitle': 'Advanced technology meets traditional beekeeping. Monitor, analyze, and protect your colonies with cutting-edge sensors and AI-powered insights.',
    'landing.testimonials.title': 'Trusted by beekeepers worldwide',
    'landing.testimonials.subtitle': 'See how Beetkar is helping beekeepers protect and optimize their operations',
    'landing.cta.title': 'Ready to revolutionize your beekeeping?',
    'landing.cta.subtitle': 'Join thousands of beekeepers who trust Beetkar to protect their colonies',
    
    // About Page
    'about.title': 'Protecting bees with',
    'about.subtitle': 'smart technology',
    'about.description': "We're on a mission to save bee colonies worldwide by combining cutting-edge technology with traditional beekeeping wisdom. Every hive matters, every bee counts.",
    'about.mission': 'Our Mission',
    'about.mission.description1': 'Bee populations worldwide are under threat from varroa mites, climate change, and environmental stressors. Traditional monitoring methods often detect problems too late to save the colony.',
    'about.mission.description2': 'Beetkar changes this by providing early warning systems that detect issues before they become critical, giving beekeepers the power to act quickly and save their colonies.',
    'about.reduction.loss': 'Reduction in colony loss',
    'about.detection.accuracy': 'Mite detection accuracy',
    'about.bee.conservation': 'Bee Conservation',
    'about.bee.conservation.desc': "We're passionate about protecting bee populations and supporting sustainable beekeeping practices worldwide.",
    'about.innovation': 'Innovation',
    'about.innovation.desc': 'Cutting-edge technology meets traditional beekeeping wisdom to create solutions that actually work.',
    'about.reliability': 'Reliability',
    'about.reliability.desc': 'Your hives depend on us. We build robust, dependable systems that work when you need them most.',
    'about.journey.title': 'Our Journey',
    'about.journey.subtitle': 'From idea to global impact - the Beetkar story',
    'about.team.title': 'Meet Our Team',
    'about.team.subtitle': 'Passionate experts combining technology and beekeeping knowledge',
    'about.recognition.title': 'Recognition',
    'about.cta.title': 'Join us in protecting bee colonies worldwide',
    'about.cta.subtitle': 'Every beekeeper who uses Beetkar helps us improve our technology and save more colonies',
    'about.cta.button': 'Start Protecting Your Hives',
    'about.cta.shop': 'Shop Devices',
    
    // Login Page
    'login.title': 'Welcome back',
    'login.subtitle': 'Sign in to monitor your beehives',
    'login.demo.title': 'Try the demo with sample data',
    'login.demo.button': 'Fill demo credentials',
    'login.email': 'Email address',
    'login.email.placeholder': 'Enter your email',
    'login.password': 'Password',
    'login.password.placeholder': 'Enter your password',
    'login.remember': 'Remember me',
    'login.forgot': 'Forgot password?',
    'login.signin': 'Sign in',
    'login.signing': 'Signing in...',
    'login.no.account': "Don't have an account?",
    'login.signup.link': 'Sign up for free',
    'login.back.home': '← Back to home',
    'login.error.email': 'Email is required',
    'login.error.email.invalid': 'Please enter a valid email address',
    'login.error.password': 'Password is required',
    'login.error.password.length': 'Password must be at least 6 characters',
    'login.error.general': 'Invalid email or password',
    
    // Signup Page
    'signup.title': 'Create your account',
    'signup.subtitle': 'Start monitoring your beehives today',
    'signup.benefits.title': "What you'll get:",
    'signup.benefits.trial': '30-day free trial',
    'signup.benefits.monitoring': 'Real-time hive monitoring',
    'signup.benefits.detection': 'AI-powered mite detection',
    'signup.benefits.alerts': 'Smart alerts & notifications',
    'signup.first.name': 'First name',
    'signup.last.name': 'Last name',
    'signup.email': 'Email address',
    'signup.password': 'Password',
    'signup.confirm.password': 'Confirm password',
    'signup.password.strength.weak': 'Weak',
    'signup.password.strength.medium': 'Medium',
    'signup.password.strength.strong': 'Strong',
    'signup.agree.terms': 'I agree to the',
    'signup.terms': 'Terms of Service',
    'signup.privacy': 'Privacy Policy',
    'signup.newsletter': 'Send me updates about new features and beekeeping tips',
    'signup.create': 'Create account',
    'signup.creating': 'Creating account...',
    'signup.have.account': 'Already have an account?',
    'signup.signin.link': 'Sign in',
    'signup.back.home': '← Back to home',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.subtitle': 'Monitor your beehives and keep them healthy',
    'dashboard.temperature': 'Temperature',
    'dashboard.humidity': 'Humidity',
    'dashboard.sound': 'Sound Level',
    'dashboard.vibration': 'Vibration',
    'dashboard.status.overview': 'Hive Status Overview',
    'dashboard.last.sync': 'Last sync',
    'dashboard.device.id': 'Device ID',
    'dashboard.signal.strength': 'Signal Strength',
    'dashboard.overall.status': 'Overall Status',
    'dashboard.quick.stats': 'Quick Stats',
    'dashboard.avg.temp': 'Avg Temperature (24h)',
    'dashboard.peak.sound': 'Peak Sound (24h)',
    'dashboard.activity.level': 'Activity Level',
    'dashboard.recent.activity': 'Recent Activity',
    'dashboard.temp.stabilized': 'Temperature stabilized',
    'dashboard.sound.increased': 'Sound level increased',
    'dashboard.data.sync': 'Data sync completed',
    'dashboard.temp.trend': 'Temperature Trend',
    'dashboard.humidity.trend': 'Humidity Trend',
    
    // Hive Details
    'hive.details.title': 'Hive Details',
    'hive.details.download': 'Download Report',
    'hive.details.thermal': 'Thermal Imaging',
    'hive.details.latest': 'Latest Image',
    'hive.details.gallery': 'Image Gallery',
    'hive.details.analysis': 'Analysis Results',
    'hive.details.mites.detected': 'Varroa Mites Detected',
    'hive.details.temp.variance': 'Temperature Variance',
    'hive.details.image.quality': 'Image Quality',
    'hive.details.excellent': 'Excellent',
    'hive.details.temp.over.time': 'Temperature Over Time',
    'hive.details.humidity.over.time': 'Humidity Over Time',
    'hive.details.sound.activity': 'Sound Activity',
    'hive.details.vibration.level': 'Vibration Level',
    'hive.details.device.status': 'Device Status',
    'hive.details.temp.sensor': 'Temperature Sensor',
    'hive.details.humidity.sensor': 'Humidity Sensor',
    'hive.details.sound.sensor': 'Sound Sensor',
    'hive.details.vibration.sensor': 'Vibration Sensor',
    'hive.details.recent.alerts': 'Recent Alerts',
    'hive.details.no.alerts': 'No alerts for this hive',
    
    // Add Hive
    'add.hive.title': 'Add New Hive',
    'add.hive.subtitle': 'Register a new beehive to your monitoring system',
    'add.hive.basic.info': 'Basic Information',
    'add.hive.name': 'Hive Name',
    'add.hive.name.placeholder': 'e.g., North Garden Hive',
    'add.hive.device.id': 'Device ID',
    'add.hive.device.placeholder': 'e.g., BK-004',
    'add.hive.location': 'Location',
    'add.hive.location.placeholder': 'e.g., West Field Plot D',
    'add.hive.photo': 'Hive Photo',
    'add.hive.photo.upload': 'Upload a photo of your hive',
    'add.hive.photo.choose': 'Choose Photo',
    'add.hive.sensor.config': 'Initial Sensor Configuration',
    'add.hive.target.temp': 'Target Temperature (°C)',
    'add.hive.target.humidity': 'Target Humidity (%)',
    'add.hive.sound.threshold': 'Sound Threshold (dB)',
    'add.hive.vibration.threshold': 'Vibration Threshold (Hz)',
    'add.hive.device.config': 'Device Configuration',
    'add.hive.initial.status': 'Initial Status',
    'add.hive.signal.strength': 'Expected Signal Strength (%)',
    'add.hive.add': 'Add Hive',
    'add.hive.adding': 'Adding Hive...',
    
    // Alerts
    'alerts.title': 'Alert Management',
    'alerts.subtitle': 'Monitor and manage your beehive alerts',
    'alerts.critical': 'Critical',
    'alerts.high.priority': 'High Priority',
    'alerts.search': 'Search alerts...',
    'alerts.status': 'Status',
    'alerts.severity': 'Severity',
    'alerts.all': 'All',
    'alerts.active': 'Active',
    'alerts.resolved': 'Resolved',
    'alerts.medium': 'Medium',
    'alerts.low': 'Low',
    'alerts.high': 'High',
    'alerts.no.alerts': 'No Alerts Found',
    'alerts.no.alerts.desc': 'All your beehives are healthy and operating normally.',
    'alerts.no.alerts.filter': 'Try adjusting your filters to see more alerts.',
    'alerts.resolve': 'Resolve',
    'alerts.resolved.status': 'Resolved',
    'alerts.details': 'Alert Details',
    'alerts.alert.id': 'Alert ID',
    'alerts.hive.id': 'Hive ID',
    'alerts.timestamp': 'Timestamp',
    'alerts.recommended.action': 'Recommended Action',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account and application preferences',
    'settings.user.profile': 'User Profile',
    'settings.full.name': 'Full Name',
    'settings.email': 'Email Address',
    'settings.role': 'Role',
    'settings.account.status': 'Account Status',
    'settings.active': 'Active',
    'settings.notifications': 'Notification Preferences',
    'settings.email.notifications': 'Email Notifications',
    'settings.email.desc': 'Receive alerts and updates via email',
    'settings.push.notifications': 'Push Notifications',
    'settings.push.desc': 'Receive instant alerts on your device',
    'settings.critical.only': 'Critical Alerts Only',
    'settings.critical.desc': 'Only receive notifications for critical issues',
    'settings.app.preferences': 'App Preferences',
    'settings.dark.mode': 'Dark Mode',
    'settings.dark.desc': 'Enable dark theme for better visibility',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.data.management': 'Data Management',
    'settings.offline.sync': 'Offline Data Sync',
    'settings.offline.desc': 'Automatically sync data when connection is restored',
    'settings.sync.now': 'Sync Offline Data Now',
    'settings.sync.desc': 'Manually sync any pending offline data',
    'settings.sync.button': 'Sync Now',
    'settings.help.support': 'Help & Support',
    'settings.contact.info': 'Contact Information',
    'settings.support.email': 'Support Email',
    'settings.support.phone': 'Support Phone',
    'settings.resources': 'Resources',
    'settings.save': 'Save Settings',
    'settings.saving': 'Saving...',
    
    // Shop
    'shop.title': 'Beetkar Smart Hive',
    'shop.subtitle': 'Monitors',
    'shop.description': 'Professional beehive monitoring systems with thermal imaging, AI-powered mite detection, and real-time alerts. Protect your colonies with cutting-edge technology.',
    'shop.free.shipping': 'Free Shipping',
    'shop.warranty': '2-Year Warranty',
    'shop.secure.payment': 'Secure Payment',
    'shop.choose.system': 'Choose Your Monitoring System',
    'shop.choose.description': 'From hobbyist to commercial operations, we have the perfect solution for your apiary',
    'shop.add.cart': 'Add to Cart',
    'shop.out.stock': 'Out of Stock',
    'shop.in.stock': 'In Stock - Ships within 2-3 business days',
    'shop.quantity': 'Quantity',
    'shop.key.features': 'Key Features',
    'shop.more.features': 'more features',
    'shop.show.less': 'Show less',
    'shop.save': 'Save',
    
    // Sidebar
    'sidebar.smart.monitor': 'Smart Beehive Monitor',
    'sidebar.beekeeper': 'Beekeeper',
    'sidebar.sign.out': 'Sign out',
    
    // Common
    'common.online': 'Online',
    'common.offline': 'Offline',
    'common.healthy': 'Healthy',
    'common.warning': 'Warning',
    'common.critical': 'Critical',
    'common.high': 'High',
    'common.owner': 'Owner',
    'common.manager': 'Manager',
    'common.viewer': 'Viewer',
    'common.guest': 'Guest',
    'common.celsius': '°C',
    'common.percent': '%',
    'common.decibel': 'dB',
    'common.hertz': 'Hz',
    'common.ago': 'ago',
    'common.now': 'Now',
    'common.just.now': 'Just now',
    'common.minutes': 'm',
    'common.hours': 'h',
    'common.days': 'd',
    'common.mites': 'mites',
  },
  ka: {
    // Navigation
    'nav.home': 'მთავარი',
    'nav.about': 'ჩვენ შესახებ',
    'nav.shop': 'მაღაზია',
    'nav.login': 'შესვლა',
    'nav.signup': 'რეგისტრაცია',
    'nav.dashboard': 'დაშბორდი',
    'nav.cart': 'კალათა',
    'nav.hive.details': 'ფუტკრის დეტალები',
    'nav.alerts': 'გაფრთხილებები',
    'nav.add.hive': 'ფუტკრის დამატება',
    'nav.settings': 'პარამეტრები',
    
    // Landing Page
    'landing.hero.title': 'ჭკვიანური ფუტკრის',
    'landing.hero.subtitle': 'მონიტორინგი',
    'landing.hero.description': 'დაიცავით თქვენი კოლონიები AI-ით მართული თერმული გამოსახულებით, რეალურ დროში სენსორებით და ინტელექტუალური გაფრთხილებებით. ადრეულად აღმოაჩინეთ ვაროა ტკიპები და ოპტიმიზაცია გაუკეთეთ ფუტკრის ჯანმრთელობას.',
    'landing.hero.cta.trial': 'უფასო ტესტის დაწყება',
    'landing.hero.cta.shop': 'მოწყობილობების შოპინგი',
    'landing.hero.benefits.trial': '30-დღიანი უფასო ტესტი',
    'landing.hero.benefits.card': 'საბანკო ბარათი არ არის საჭირო',
    'landing.stats.hives': 'მონიტორინგი გაკეთებული ფუტკრები',
    'landing.stats.accuracy': 'ტკიპების აღმოჩენის სიზუსტე',
    'landing.stats.reduction': 'კოლონიის დაკარგვის შემცირება',
    'landing.stats.monitoring': 'უწყვეტი მონიტორინგი',
    'landing.features.title': 'ყველაფერი რაც გჭირდებათ თქვენი ფუტკრების დასაცავად',
    'landing.features.subtitle': 'უახლესი ტექნოლოგია ხვდება ტრადიციულ მეფუტკრეობას. მონიტორინგი, ანალიზი და დაცვა გაუკეთეთ თქვენს კოლონიებს უახლესი სენსორებით და AI-ით მართული ანალიტიკით.',
    'landing.testimonials.title': 'ნდობით სარგებლობს მეფუტკრეები მთელ მსოფლიოში',
    'landing.testimonials.subtitle': 'იხილეთ როგორ ეხმარება Beetkar მეფუტკრეებს თავიანთი ოპერაციების დაცვასა და ოპტიმიზაციაში',
    'landing.cta.title': 'მზად ხართ რევოლუცია მოახდინოთ თქვენს მეფუტკრეობაში?',
    'landing.cta.subtitle': 'შეუერთდით ათასობით მეფუტკრეს, რომლებიც ენდობიან Beetkar-ს თავიანთი კოლონიების დასაცავად',
    
    // About Page
    'about.title': 'ფუტკრების დაცვა',
    'about.subtitle': 'ჭკვიანური ტექნოლოგიით',
    'about.description': 'ჩვენი მისიაა მსოფლიოში ფუტკრის კოლონიების გადარჩენა უახლესი ტექნოლოგიის და ტრადიციული მეფუტკრეობის ცოდნის შერწყმით. ყველა ფუტკარი მნიშვნელოვანია, ყველა ფუტკარი ითვლება.',
    'about.mission': 'ჩვენი მისია',
    'about.mission.description1': 'ფუტკრის პოპულაციები მთელ მსოფლიოში საფრთხის ქვეშ არიან ვაროა ტკიპების, კლიმატის ცვლილების და გარემოსდაცვითი სტრესების გამო. ტრადიციული მონიტორინგის მეთოდები ხშირად ძალიან გვიან აღმოაჩენენ პრობლემებს კოლონიის გადასარჩენად.',
    'about.mission.description2': 'Beetkar ამას ცვლის ადრეული გაფრთხილების სისტემების უზრუნველყოფით, რომლებიც პრობლემებს კრიტიკულ გახდომამდე აღმოაჩენენ, რაც მეფუტკრეებს ძალას აძლევს სწრაფად იმოქმედონ და გადაარჩინონ თავიანთი კოლონიები.',
    'about.reduction.loss': 'კოლონიის დაკარგვის შემცირება',
    'about.detection.accuracy': 'ტკიპების აღმოჩენის სიზუსტე',
    'about.bee.conservation': 'ფუტკრების კონსერვაცია',
    'about.bee.conservation.desc': 'ჩვენ გვიყვარს ფუტკრის პოპულაციების დაცვა და მდგრადი მეფუტკრეობის პრაქტიკის მხარდაჭერა მთელ მსოფლიოში.',
    'about.innovation': 'ინოვაცია',
    'about.innovation.desc': 'უახლესი ტექნოლოგია ხვდება ტრადიციულ მეფუტკრეობის ცოდნას, რათა შექმნას გადაწყვეტები, რომლებიც ნამდვილად მუშაობს.',
    'about.reliability': 'საიმედოობა',
    'about.reliability.desc': 'თქვენი ფუტკრები ჩვენზე არიან დამოკიდებული. ჩვენ ვაშენებთ მტკიცე, საიმედო სისტემებს, რომლებიც მუშაობს, როცა ისინი გჭირდებათ.',
    'about.journey.title': 'ჩვენი მოგზაურობა',
    'about.journey.subtitle': 'იდეიდან გლობალურ ზეგავლენამდე - Beetkar-ის ისტორია',
    'about.team.title': 'გაიცანით ჩვენი გუნდი',
    'about.team.subtitle': 'ვნებიანი ექსპერტები, რომლებიც აერთიანებენ ტექნოლოგიას და მეფუტკრეობის ცოდნას',
    'about.recognition.title': 'აღიარება',
    'about.cta.title': 'შეუერთდით ჩვენ ფუტკრის კოლონიების დაცვაში მთელ მსოფლიოში',
    'about.cta.subtitle': 'ყველა მეფუტკრე, რომელიც იყენებს Beetkar-ს, გვეხმარება ჩვენი ტექნოლოგიის გაუმჯობესებასა და მეტი კოლონიის გადარჩენაში',
    'about.cta.button': 'დაიწყეთ თქვენი ფუტკრების დაცვა',
    'about.cta.shop': 'მოწყობილობების შოპინგი',
    
    // Login Page
    'login.title': 'კეთილი იყოს თქვენი დაბრუნება',
    'login.subtitle': 'შედით თქვენი ფუტკრების მონიტორინგისთვის',
    'login.demo.title': 'სცადეთ დემო ნიმუშის მონაცემებით',
    'login.demo.button': 'შეავსეთ დემო მონაცემები',
    'login.email': 'ელ-ფოსტის მისამართი',
    'login.email.placeholder': 'შეიყვანეთ თქვენი ელ-ფოსტა',
    'login.password': 'პაროლი',
    'login.password.placeholder': 'შეიყვანეთ თქვენი პაროლი',
    'login.remember': 'დამიმახსოვრე',
    'login.forgot': 'დაგავიწყდათ პაროლი?',
    'login.signin': 'შესვლა',
    'login.signing': 'შესვლა...',
    'login.no.account': 'არ გაქვთ ანგარიში?',
    'login.signup.link': 'უფასოდ დარეგისტრირდით',
    'login.back.home': '← უკან მთავარზე',
    'login.error.email': 'ელ-ფოსტა აუცილებელია',
    'login.error.email.invalid': 'გთხოვთ შეიყვანოთ სწორი ელ-ფოსტის მისამართი',
    'login.error.password': 'პაროლი აუცილებელია',
    'login.error.password.length': 'პაროლი უნდა იყოს მინიმუმ 6 სიმბოლო',
    'login.error.general': 'არასწორი ელ-ფოსტა ან პაროლი',
    
    // Signup Page
    'signup.title': 'შექმენით თქვენი ანგარიში',
    'signup.subtitle': 'დაიწყეთ თქვენი ფუტკრების მონიტორინგი დღესვე',
    'signup.benefits.title': 'რას მიიღებთ:',
    'signup.benefits.trial': '30-დღიანი უფასო ტესტი',
    'signup.benefits.monitoring': 'რეალურ დროში ფუტკრის მონიტორინგი',
    'signup.benefits.detection': 'AI-ით მართული ტკიპების აღმოჩენა',
    'signup.benefits.alerts': 'ჭკვიანური გაფრთხილებები და შეტყობინებები',
    'signup.first.name': 'სახელი',
    'signup.last.name': 'გვარი',
    'signup.email': 'ელ-ფოსტის მისამართი',
    'signup.password': 'პაროლი',
    'signup.confirm.password': 'დაადასტურეთ პაროლი',
    'signup.password.strength.weak': 'სუსტი',
    'signup.password.strength.medium': 'საშუალო',
    'signup.password.strength.strong': 'ძლიერი',
    'signup.agree.terms': 'ვეთანხმები',
    'signup.terms': 'მომსახურების პირობებს',
    'signup.privacy': 'კონფიდენციალურობის პოლიტიკას',
    'signup.newsletter': 'გამომიგზავნეთ განახლებები ახალი ფუნქციებისა და მეფუტკრეობის რჩევების შესახებ',
    'signup.create': 'ანგარიშის შექმნა',
    'signup.creating': 'ანგარიშის შექმნა...',
    'signup.have.account': 'უკვე გაქვთ ანგარიში?',
    'signup.signin.link': 'შესვლა',
    'signup.back.home': '← უკან მთავარზე',
    
    // Dashboard
    'dashboard.welcome': 'კეთილი იყოს თქვენი დაბრუნება',
    'dashboard.subtitle': 'მონიტორინგი გაუკეთეთ თქვენს ფუტკრებს და შეინარჩუნეთ მათი ჯანმრთელობა',
    'dashboard.temperature': 'ტემპერატურა',
    'dashboard.humidity': 'ტენიანობა',
    'dashboard.sound': 'ხმის დონე',
    'dashboard.vibration': 'ვიბრაცია',
    'dashboard.status.overview': 'ფუტკრის სტატუსის მიმოხილვა',
    'dashboard.last.sync': 'ბოლო სინქრონიზაცია',
    'dashboard.device.id': 'მოწყობილობის ID',
    'dashboard.signal.strength': 'სიგნალის სიძლიერე',
    'dashboard.overall.status': 'საერთო სტატუსი',
    'dashboard.quick.stats': 'სწრაფი სტატისტიკა',
    'dashboard.avg.temp': 'საშუალო ტემპერატურა (24სთ)',
    'dashboard.peak.sound': 'მაქსიმალური ხმა (24სთ)',
    'dashboard.activity.level': 'აქტივობის დონე',
    'dashboard.recent.activity': 'ბოლო აქტივობა',
    'dashboard.temp.stabilized': 'ტემპერატურა სტაბილიზებულია',
    'dashboard.sound.increased': 'ხმის დონე გაიზარდა',
    'dashboard.data.sync': 'მონაცემთა სინქრონიზაცია დასრულდა',
    'dashboard.temp.trend': 'ტემპერატურის ტენდენცია',
    'dashboard.humidity.trend': 'ტენიანობის ტენდენცია',
    
    // Hive Details
    'hive.details.title': 'ფუტკრის დეტალები',
    'hive.details.download': 'რეპორტის ჩამოტვირთვა',
    'hive.details.thermal': 'თერმული გამოსახულება',
    'hive.details.latest': 'უახლესი გამოსახულება',
    'hive.details.gallery': 'გამოსახულებების გალერეა',
    'hive.details.analysis': 'ანალიზის შედეგები',
    'hive.details.mites.detected': 'აღმოჩენილი ვაროა ტკიპები',
    'hive.details.temp.variance': 'ტემპერატურის ვარიაცია',
    'hive.details.image.quality': 'გამოსახულების ხარისხი',
    'hive.details.excellent': 'შესანიშნავი',
    'hive.details.temp.over.time': 'ტემპერატურა დროის მიხედვით',
    'hive.details.humidity.over.time': 'ტენიანობა დროის მიხედვით',
    'hive.details.sound.activity': 'ხმოვანი აქტივობა',
    'hive.details.vibration.level': 'ვიბრაციის დონე',
    'hive.details.device.status': 'მოწყობილობის სტატუსი',
    'hive.details.temp.sensor': 'ტემპერატურის სენსორი',
    'hive.details.humidity.sensor': 'ტენიანობის სენსორი',
    'hive.details.sound.sensor': 'ხმის სენსორი',
    'hive.details.vibration.sensor': 'ვიბრაციის სენსორი',
    'hive.details.recent.alerts': 'ბოლო გაფრთხილებები',
    'hive.details.no.alerts': 'ამ ფუტკარზე გაფრთხილებები არ არის',
    
    // Add Hive
    'add.hive.title': 'ახალი ფუტკრის დამატება',
    'add.hive.subtitle': 'დარეგისტრირეთ ახალი ფუტკარი თქვენს მონიტორინგის სისტემაში',
    'add.hive.basic.info': 'ძირითადი ინფორმაცია',
    'add.hive.name': 'ფუტკრის სახელი',
    'add.hive.name.placeholder': 'მაგ., ჩრდილოეთ ბაღის ფუტკარი',
    'add.hive.device.id': 'მოწყობილობის ID',
    'add.hive.device.placeholder': 'მაგ., BK-004',
    'add.hive.location': 'მდებარეობა',
    'add.hive.location.placeholder': 'მაგ., დასავლეთ ველის ნაკვეთი D',
    'add.hive.photo': 'ფუტკრის ფოტო',
    'add.hive.photo.upload': 'ატვირთეთ თქვენი ფუტკრის ფოტო',
    'add.hive.photo.choose': 'ფოტოს არჩევა',
    'add.hive.sensor.config': 'სენსორის საწყისი კონფიგურაცია',
    'add.hive.target.temp': 'სამიზნე ტემპერატურა (°C)',
    'add.hive.target.humidity': 'სამიზნე ტენიანობა (%)',
    'add.hive.sound.threshold': 'ხმის ზღვარი (dB)',
    'add.hive.vibration.threshold': 'ვიბრაციის ზღვარი (Hz)',
    'add.hive.device.config': 'მოწყობილობის კონფიგურაცია',
    'add.hive.initial.status': 'საწყისი სტატუსი',
    'add.hive.signal.strength': 'მოსალოდნელი სიგნალის სიძლიერე (%)',
    'add.hive.add': 'ფუტკრის დამატება',
    'add.hive.adding': 'ფუტკრის დამატება...',
    
    // Alerts
    'alerts.title': 'გაფრთხილებების მართვა',
    'alerts.subtitle': 'მონიტორინგი და მართვა გაუკეთეთ თქვენი ფუტკრის გაფრთხილებებს',
    'alerts.critical': 'კრიტიკული',
    'alerts.high.priority': 'მაღალი პრიორიტეტი',
    'alerts.search': 'გაფრთხილებების ძიება...',
    'alerts.status': 'სტატუსი',
    'alerts.severity': 'სიმძიმე',
    'alerts.all': 'ყველა',
    'alerts.active': 'აქტიური',
    'alerts.resolved': 'გადაწყვეტილი',
    'alerts.medium': 'საშუალო',
    'alerts.low': 'დაბალი',
    'alerts.high': 'მაღალი',
    'alerts.no.alerts': 'გაფრთხილებები ვერ მოიძებნა',
    'alerts.no.alerts.desc': 'ყველა თქვენი ფუტკარი ჯანმრთელია და ნორმალურად ფუნქციონირებს.',
    'alerts.no.alerts.filter': 'სცადეთ ფილტრების რეგულირება მეტი გაფრთხილების სანახავად.',
    'alerts.resolve': 'გადაწყვეტა',
    'alerts.resolved.status': 'გადაწყვეტილი',
    'alerts.details': 'გაფრთხილების დეტალები',
    'alerts.alert.id': 'გაფრთხილების ID',
    'alerts.hive.id': 'ფუტკრის ID',
    'alerts.timestamp': 'დროის ნიშანი',
    'alerts.recommended.action': 'რეკომენდებული მოქმედება',
    
    // Settings
    'settings.title': 'პარამეტრები',
    'settings.subtitle': 'მართეთ თქვენი ანგარიში და აპლიკაციის პრეფერენციები',
    'settings.user.profile': 'მომხმარებლის პროფილი',
    'settings.full.name': 'სრული სახელი',
    'settings.email': 'ელ-ფოსტის მისამართი',
    'settings.role': 'როლი',
    'settings.account.status': 'ანგარიშის სტატუსი',
    'settings.active': 'აქტიური',
    'settings.notifications': 'შეტყობინებების პრეფერენციები',
    'settings.email.notifications': 'ელ-ფოსტის შეტყობინებები',
    'settings.email.desc': 'მიიღეთ გაფრთხილებები და განახლებები ელ-ფოსტით',
    'settings.push.notifications': 'Push შეტყობინებები',
    'settings.push.desc': 'მიიღეთ მყისიერი გაფრთხილებები თქვენს მოწყობილობაზე',
    'settings.critical.only': 'მხოლოდ კრიტიკული გაფრთხილებები',
    'settings.critical.desc': 'მიიღეთ შეტყობინებები მხოლოდ კრიტიკული საკითხებისთვის',
    'settings.app.preferences': 'აპლიკაციის პრეფერენციები',
    'settings.dark.mode': 'მუქი რეჟიმი',
    'settings.dark.desc': 'ჩართეთ მუქი თემა უკეთესი ხილვადობისთვის',
    'settings.light': 'ნათელი',
    'settings.dark': 'მუქი',
    'settings.data.management': 'მონაცემთა მართვა',
    'settings.offline.sync': 'ოფლაინ მონაცემთა სინქრონიზაცია',
    'settings.offline.desc': 'ავტომატურად სინქრონიზაცია გაუკეთეთ მონაცემებს კავშირის აღდგენისას',
    'settings.sync.now': 'ოფლაინ მონაცემების სინქრონიზაცია ახლა',
    'settings.sync.desc': 'ხელით სინქრონიზაცია გაუკეთეთ ნებისმიერ მომლოდინე ოფლაინ მონაცემებს',
    'settings.sync.button': 'სინქრონიზაცია ახლა',
    'settings.help.support': 'დახმარება და მხარდაჭერა',
    'settings.contact.info': 'საკონტაქტო ინფორმაცია',
    'settings.support.email': 'მხარდაჭერის ელ-ფოსტა',
    'settings.support.phone': 'მხარდაჭერის ტელეფონი',
    'settings.resources': 'რესურსები',
    'settings.save': 'პარამეტრების შენახვა',
    'settings.saving': 'შენახვა...',
    
    // Shop
    'shop.title': 'Beetkar ჭკვიანური ფუტკრის',
    'shop.subtitle': 'მონიტორები',
    'shop.description': 'პროფესიონალური ფუტკრის მონიტორინგის სისტემები თერმული გამოსახულებით, AI-ით მართული ტკიპების აღმოჩენით და რეალურ დროში გაფრთხილებებით. დაიცავით თქვენი კოლონიები უახლესი ტექნოლოგიით.',
    'shop.free.shipping': 'უფასო მიწოდება',
    'shop.warranty': '2-წლიანი გარანტია',
    'shop.secure.payment': 'უსაფრთხო გადახდა',
    'shop.choose.system': 'აირჩიეთ თქვენი მონიტორინგის სისტემა',
    'shop.choose.description': 'ჰობისტებიდან კომერციულ ოპერაციებამდე, ჩვენ გვაქვს იდეალური გადაწყვეტა თქვენი მეფუტკრეობისთვის',
    'shop.add.cart': 'კალათაში დამატება',
    'shop.out.stock': 'არ არის მარაგში',
    'shop.in.stock': 'მარაგშია - გაიგზავნება 2-3 სამუშაო დღეში',
    'shop.quantity': 'რაოდენობა',
    'shop.key.features': 'მთავარი ფუნქციები',
    'shop.more.features': 'მეტი ფუნქცია',
    'shop.show.less': 'ნაკლების ჩვენება',
    'shop.save': 'დაზოგვა',
    
    // Sidebar
    'sidebar.smart.monitor': 'ჭკვიანური ფუტკრის მონიტორი',
    'sidebar.beekeeper': 'მეფუტკრე',
    'sidebar.sign.out': 'გასვლა',
    
    // Common
    'common.online': 'ონლაინ',
    'common.offline': 'ოფლაინ',
    'common.healthy': 'ჯანმრთელი',
    'common.warning': 'გაფრთხილება',
    'common.critical': 'კრიტიკული',
    'common.high': 'მაღალი',
    'common.owner': 'მფლობელი',
    'common.manager': 'მენეჯერი',
    'common.viewer': 'მნახველი',
    'common.guest': 'სტუმარი',
    'common.celsius': '°C',
    'common.percent': '%',
    'common.decibel': 'დბ',
    'common.hertz': 'ჰც',
    'common.ago': 'წინ',
    'common.now': 'ახლა',
    'common.just.now': 'ახლახან',
    'common.minutes': 'წთ',
    'common.hours': 'სთ',
    'common.days': 'დღ',
    'common.mites': 'ტკიპები',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};